name: Code Review

on:
    pull_request:
        types: [ opened, reopened, synchronize ]

permissions:
    pull-requests: write
    contents: read

jobs:
    review:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: ChatGPT Code Review
                uses: anc95/ChatGPT-CodeReview@main
                prompt: ${{OPENAI_PROMPT}}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                    LANGUAGE: ko
                    MODEL: gpt-4
                    TEMPERATURE: 0.7
                    MAX_TOKENS: 2048
